language: r
cache: packages

matrix:
  include:
    - os: linux
      r: release
      sudo : false
    - os: linux
      r: devel
      sudo : false
    - os: osx
      latex: false
      r: devel
    - os: osx
      latex: false
      r: release
  allow_failures:
    - os: osx
    
addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev
      - libudunits2-dev
      - netcdf-bin
      - libmpfr-dev
      
env:
 global:
   - _R_CHECK_FORCE_SUGGESTS_: false